site_name: DCSS Morgue Analyser
repo_url: https://github.com/MarshP/dcss_morgue_analyser
edit_uri: edit/master/docs/
site_description: Analyse your DCSS morgue
pages:
  - Home: index.md
  - Quick-Start: quick-start.md
theme: windmill
docs_dir: ./docs_source
site_dir: ./docs
markdown_extensions:
  - extra